version: "3.8"

services:
  db:
    image: postgres:16.3-alpine
    container_name: hrims-db
    restart: always
    environment:
      POSTGRES_DB: hrims_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: .
    container_name: hrims-backend
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/hrims_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      # comment below if  not using .env file instead
      env_file: .env

volumes:
  pgdata:
